// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package links

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID        int64
	Url       string
	ShortName string
}

type Visit struct {
	ID        int64
	LinkID    int32
	CreatedAt pgtype.Timestamptz
	Ip        string
	UserAgent pgtype.Text
	Status    pgtype.Int4
}
