// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package links

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (url, short_name)
VALUES ($1, $2)
RETURNING id
`

type CreateLinkParams struct {
	Url       string
	ShortName string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLink, arg.Url, arg.ShortName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLink = `-- name: DeleteLink :execresult
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteLink, id)
}

const getLink = `-- name: GetLink :one
SELECT id, url, short_name FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(&i.ID, &i.Url, &i.ShortName)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, url, short_name FROM links
`

func (q *Queries) GetLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.Url, &i.ShortName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :execresult
UPDATE links
SET url = $1,
    short_name = $2
WHERE id = $3
`

type UpdateLinkParams struct {
	Url       string
	ShortName string
	ID        int64
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateLink, arg.Url, arg.ShortName, arg.ID)
}
